apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: Starter Project For Spring Boot in Kotlin.
spec:
  type: service
  owner: ${{ values.owner | dump }}
  lifecycle: experimental
